from setuptools import setup

setup(
    name='tensiga',
    version='0.1.0',
    author='Michał Ł. Mika',
    author_email='ydL7N734vsoNV@mika.sh',
    packages=['tensiga'],
    scripts=[
        'bin/ibq_galerkin1d.py',
        'bin/ibq_galerkin2d.py',
        'bin/ibq_galerkin3d.py',
        'bin/ibq_mf_galerkin1d.py',
        'bin/ibq_mf_galerkin2d.py',
        'bin/ibq_mf_galerkin3d.py',
        'bin/ibq_galerkin1d.py',
        'bin/kron_galerkin1d.py',
        'bin/kron_galerkin1d.py',
        'bin/kron_galerkin1d.py',
    ],
    url='http://pypi.python.org/pypi/tensiga/',
    license='LICENSE',
    description="Implementation of a matrix-free isogeometric Galerkin method for Karhunen-Loeve approximation of random fields using tensor product splines, tensor contraction and interpolation based quadrature",
    long_description=open('README.md').read(),
    install_requires=[
        "pytest",
        "numpy",
        "numba",
        "scipy",
        "scikit-sparse",
        "sklearn",
        "sharedmem",
        "vtk",
        "pyvista",
        "matplotlib",
    ],
)
